export const OPENCODE_WORKFLOW_FILES = [
  'development-rules.md',
  'documentation-management.md',
  'orchestration-protocol.md',
  'primary-workflow.md',
] as const

export const OPENCODE_AGENT_DESCRIPTIONS: Record<string, string> = {
  brainstormer: 'Debates solution options, tradeoffs, and product direction before implementation.',
  'code-reviewer': 'Reviews code for bugs, regressions, security risks, and missing work.',
  copywriter: 'Writes and improves product, UI, and marketing copy.',
  'database-admin': 'Handles schema design, query quality, and database operations.',
  debugger: 'Investigates root causes, reproduces issues, and guides fixes.',
  'docs-manager': 'Creates and updates project documentation under docs/.',
  'git-manager': 'Stages, commits, pushes, and helps with pull request workflows.',
  'journal-writer': 'Writes development journal entries and status notes.',
  'mcp-manager': 'Discovers and executes MCP tools while keeping the main context clean.',
  planner: 'Researches the codebase and produces phased implementation plans.',
  'project-manager': 'Maintains roadmap, task status, and delivery progress.',
  'refactor-cleaner': 'Finds dead code and performs careful cleanup refactors.',
  researcher: 'Performs web and docs research and returns concise technical findings.',
  'scout-external': 'Scouts external tools, docs, and reference implementations.',
  scout: 'Searches the codebase quickly and returns the most relevant files.',
  'security-reviewer': 'Performs focused security review and hardening guidance.',
  tester: 'Runs builds and tests, diagnoses failures, and verifies fixes.',
  'text-to-sql': 'Manages the semantic SQL layer and generates validated SQL from natural language.',
  'ui-ux-designer': 'Designs and implements UI with strong visual and UX standards.',
}

export const OPENCODE_COMMAND_AGENT_MAP = new Map<string, string>([
  ['vk:ask', 'brainstormer'],
  ['vk:brainstorm', 'brainstormer'],
  ['vk:content:cro', 'copywriter'],
  ['vk:content:enhance', 'copywriter'],
  ['vk:content:fast', 'copywriter'],
  ['vk:content:good', 'copywriter'],
  ['vk:debug', 'debugger'],
  ['vk:design:3d', 'ui-ux-designer'],
  ['vk:design:describe', 'ui-ux-designer'],
  ['vk:design:fast', 'ui-ux-designer'],
  ['vk:design:good', 'ui-ux-designer'],
  ['vk:design:screenshot', 'ui-ux-designer'],
  ['vk:design:video', 'ui-ux-designer'],
  ['vk:docs:init', 'docs-manager'],
  ['vk:docs:summarize', 'docs-manager'],
  ['vk:docs:update', 'docs-manager'],
  ['vk:git:cm', 'git-manager'],
  ['vk:git:cp', 'git-manager'],
  ['vk:git:pr', 'git-manager'],
  ['vk:journal', 'journal-writer'],
  ['vk:plan', 'planner'],
  ['vk:plan:ci', 'planner'],
  ['vk:plan:cro', 'planner'],
  ['vk:plan:fast', 'planner'],
  ['vk:plan:hard', 'planner'],
  ['vk:plan:two', 'planner'],
  ['vk:refactor-clean', 'refactor-cleaner'],
  ['vk:review:codebase', 'code-reviewer'],
  ['vk:scout', 'scout'],
  ['vk:scout:ext', 'scout-external'],
  ['vk:sql', 'text-to-sql'],
  ['vk:sql:manage', 'text-to-sql'],
  ['vk:sql:optimize', 'text-to-sql'],
  ['vk:sql:setup', 'text-to-sql'],
  ['vk:test', 'tester'],
  ['vk:use-mcp', 'mcp-manager'],
])

export const OPENCODE_COMMAND_ROOTS = [
  'ask',
  'brainstorm',
  'bootstrap',
  'code',
  'content',
  'cook',
  'debug',
  'design',
  'docs',
  'fix',
  'git',
  'integrate',
  'journal',
  'plan',
  'refactor-clean',
  'review',
  'scout',
  'skill',
  'sql',
  'test',
  'use-mcp',
  'watzup',
] as const
